let products = [
    {
        product_code: 'R0194903',
        product_model: '1-9490M',
        product_label: 'Kit gants attenants M ',
        product_description: 'Kit Rolock 9801 with gloves 9490 M',
        product_quantity: 0,
    },
    {
        product_code: 'R0294904',
        product_model: '2-9490L',
        product_label: 'Kit gants attenants L',
        product_description: 'Kit Rolock 9802 with gloves 9490 L',
        product_quantity: 0,
    },
    {
        product_code: 'R0294905',
        product_model: '2-9490XL',
        product_label: 'Kit gants attenants XL',
        product_description: 'Kit Rolock 9802 with gloves 9490 XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0394952',
        product_model: '3-9495S',
        product_label: 'Kit gants bleus S',
        product_description: 'Kit Rolock 9801 with gloves 9495 S',
        product_quantity: 0,
    },
    {
        product_code: 'R0394953',
        product_model: '3-9495M',
        product_label: 'Kit gants bleus M',
        product_description: 'Kit Rolock 9801 with gloves 9495 M',
        product_quantity: 0,
    },
    {
        product_code: 'R0394954',
        product_model: '3-9495L',
        product_label: 'Kit gants bleus L',
        product_description: 'Kit Rolock 9801 with gloves 9495 L',
        product_quantity: 0,
    },
    {
        product_code: 'R0394955',
        product_model: '3-9495XL',
        product_label: 'Kit gants bleus XL',
        product_description: 'Kit Rolock 9801 with gloves 9495 XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0358093',
        product_model: '3-5809M',
        product_label: 'Kit gants latex noir M',
        product_description: 'Kit Rolock 9801 with gloves 5809 M',
        product_quantity: 0,
    },
    {
        product_code: 'R0358104',
        product_model: '3-5810L',
        product_label: 'Kit gants latex noir L',
        product_description: 'Kit Rolock 9801 with gloves 5810 L',
        product_quantity: 0,
    },
    {
        product_code: 'R0358115',
        product_model: '3-5811XL',
        product_label: 'Kit gants latex noir XL',
        product_description: 'Kit Rolock 9801 with gloves 5811 XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0094903',
        product_model: '9490M',
        product_label: 'Gants fourrés M',
        product_description: 'Blue drygloves, fixed underglove, size M',
        product_quantity: 0,
    },
    {
        product_code: 'R0094904',
        product_model: '9490L',
        product_label: 'Gants fourrés L',
        product_description: 'Blue drygloves, fixed underglove, size L',
        product_quantity: 0,
    },
    {
        product_code: 'R0094905',
        product_model: '9490XL',
        product_label: 'Gants fourrés XL',
        product_description: 'Blue drygloves, fixed underglove, size XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0094952',
        product_model: '9495S',
        product_label: 'Gants amovibles S',
        product_description: 'Blue drygloves, removable underglove, size S',
        product_quantity: 0,
    },
    {
        product_code: 'R0094953',
        product_model: '9495M',
        product_label: 'Gants amovibles M',
        product_description: 'Blue drygloves, removable underglove, size M',
        product_quantity: 0,
    },
    {
        product_code: 'R0094954',
        product_model: '9495L',
        product_label: 'Gants amovibles L',
        product_description: 'Blue drygloves, removable underglove, size L',
        product_quantity: 0,
    },
    {
        product_code: 'R0094955',
        product_model: '9495XL',
        product_label: 'Gants amovibles XL',
        product_description: 'Blue drygloves, removable underglove, size XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0058093',
        product_model: '5809M',
        product_label: 'Gants latex noir M',
        product_description:
            'Drygloves latex black, separated underglove, size M',
        product_quantity: 0,
    },
    {
        product_code: 'R0058104',
        product_model: '5810L',
        product_label: 'Gants latex noir L',
        product_description:
            'Drygloves latex black, separated underglove, size L',
        product_quantity: 0,
    },
    {
        product_code: 'R0058115',
        product_model: '5811XL',
        product_label: 'Gants latex noir XL',
        product_description:
            'Drygloves latex black, separated underglove, size XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0080083',
        product_model: '8008',
        product_label: 'Sous-gants marine M',
        product_description: 'Thinsulate undergloves navy blue, size M',
        product_quantity: 0,
    },
    {
        product_code: 'R0080094',
        product_model: '8009',
        product_label: 'Sous-gants marine L',
        product_description: 'Thinsulate undergloves navy blue, size L',
        product_quantity: 0,
    },
    {
        product_code: 'R0080105',
        product_model: '8010',
        product_label: 'Sous-gants marine XL',
        product_description: 'Thinsulate undergloves navy blue, size XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0021683',
        product_model: '2168 M',
        product_label: 'Sous-gants noir M',
        product_description: 'Thermoacryl undergloves, size M',
        product_quantity: 0,
    },
    {
        product_code: 'R0021694',
        product_model: '2169 L',
        product_label: 'Sous-gants noir L',
        product_description: 'Thermoacryl undergloves, size L',
        product_quantity: 0,
    },
    {
        product_code: 'R0021605',
        product_model: '2160 XL',
        product_label: 'Sous-gants noir XL',
        product_description: 'Thermoacryl undergloves, size XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0081010',
        product_model: '8101',
        product_label: 'Cache oreille S/M',
        product_description: 'Fleece headband, size S/M',
        product_quantity: 0,
    },
    {
        product_code: 'R0081020',
        product_model: '8102',
        product_label: 'Cache oreille L/XL',
        product_description: 'Fleece headband, size L/XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0095000',
        product_model: '9500',
        product_label: 'Protection manchette',
        product_description: 'Wrist seals protection black',
        product_quantity: 0,
    },
    {
        product_code: 'R0098010',
        product_model: '9801',
        product_label: 'Kit Rolock 1',
        product_description: 'Kit Rolock 1, for gloves 9490 M',
        product_quantity: 0,
    },
    {
        product_code: 'R0098020',
        product_model: '9802',
        product_label: 'Kit Rolock 2',
        product_description: 'Kit Rolock 2, for gloves 9490 L/XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0098030',
        product_model: '9803',
        product_label: 'Kit Rolock 3',
        product_description: 'Kit Rolock 3, for gloves 9495 S/M/L/XL',
        product_quantity: 0,
    },
    {
        product_code: 'R0097070',
        product_model: '9707L',
        product_label: 'Bague gant gauche',
        product_description: 'Glove side ring, left',
        product_quantity: 0,
    },
    {
        product_code: 'R0097071',
        product_model: '9707R',
        product_label: 'Bague gant droite',
        product_description: 'Glove side ring, right',
        product_quantity: 0,
    },
    {
        product_code: 'R0097080',
        product_model: '9708L',
        product_label: 'Bague combi gauche',
        product_description: 'Drysuit side ring, left',
        product_quantity: 0,
    },
    {
        product_code: 'R0097081',
        product_model: '9708R',
        product_label: 'Bague combi droite',
        product_description: 'Drysuit side ring, right',
        product_quantity: 0,
    },
    {
        product_code: 'R0099010',
        product_model: '9901',
        product_label: 'Bague bleue',
        product_description: 'Blue ring - for kit Rolock 1',
        product_quantity: 0,
    },
    {
        product_code: 'R0099020',
        product_model: '9902',
        product_label: 'Bague noire',
        product_description: 'Black ring - for kit Rolock 2',
        product_quantity: 0,
    },
    {
        product_code: 'R0099030',
        product_model: '9903',
        product_label: 'Bague rouge',
        product_description: 'Red ring - for kit Rolock 3',
        product_quantity: 0,
    },
    {
        product_code: 'R0097010',
        product_model: '9701',
        product_label: 'Kit entretien 9802',
        product_description: 'Care and O-rings set for RoLock 9802',
        product_quantity: 0,
    },
    {
        product_code: 'R0097020',
        product_model: '9702',
        product_label: 'Kit entretien 9801/9803',
        product_description: 'Care and O-rings set for RoLock 9801 and 9803',
        product_quantity: 0,
    },
    {
        product_code: 'R0097030',
        product_model: '9703',
        product_label: 'O-ring (96x2.5) NEW',
        product_description:
            'O-Rings for bayonet lock, from 2006 (ø96x2.5), pair',
        product_quantity: 0,
    },
    {
        product_code: 'R0097040',
        product_model: '9704',
        product_label: 'O-ring (90x2) OLD',
        product_description:
            'O-Rings for bayonet lock, up to 2006 (ø90x2), pair',
        product_quantity: 0,
    },
    {
        product_code: 'R0097050',
        product_model: '9705',
        product_label: 'O-ring (65x5)',
        product_description: 'O-Rings for drysuit mounting (ø65x5), pair',
        product_quantity: 0,
    },
    {
        product_code: 'R0097060',
        product_model: '9706',
        product_label: 'O-ring (70x3)',
        product_description: 'O-rings for red ring (ø70x3), pair',
        product_quantity: 0,
    },
    {
        product_code: 'R0028980',
        product_model: 'SIP4',
        product_label: 'Silicone',
        product_description: 'Silicone grease',
        product_quantity: 0,
    },
    {
        product_code: 'R0090910',
        product_model: '9091',
        product_label: 'Kit uniquement',
        product_description: 'Kit Rolock 90, no gloves, no wrist seal',
        product_quantity: 0,
    },
    {
        product_code: 'R0090920',
        product_model: '9092',
        product_label: 'Bague PU',
        product_description: 'PU ring to be glued, pair',
        product_quantity: 0,
    },
    {
        product_code: 'R0090930',
        product_model: '9093',
        product_label: 'Manchons Silicone M',
        product_description: 'Pair of silicone wrist seal, size M',
        product_quantity: 0,
    },
    {
        product_code: 'R0090940',
        product_model: '9094',
        product_label: 'Manchons Silicone L',
        product_description: 'Pair of silicone wrist seal, size L',
        product_quantity: 0,
    },
    {
        product_code: 'R9094903',
        product_model: '90-9490M',
        product_label: 'Kit gants attenants M ',
        product_description:
            'Kit Rolock 90 with gloves 9490M, no silicone wrist seal',
        product_quantity: 0,
    },
    {
        product_code: 'R9094904',
        product_model: '90-9490L',
        product_label: 'Kit gants attenants L',
        product_description:
            'Kit Rolock 90 with gloves 9490L, no silicone wrist seal',
        product_quantity: 0,
    },
    {
        product_code: 'R9094905',
        product_model: '90-9490XL',
        product_label: 'Kit gants attenants XL',
        product_description:
            'Kit Rolock 90 with gloves 9495L, no silicone wrist seal',
        product_quantity: 0,
    },
    {
        product_code: 'R9094952',
        product_model: '90-9495S',
        product_label: 'Kit gants bleus S',
        product_description:
            'Kit Rolock 90 with gloves 9495S, no Silicone wrist seals',
        product_quantity: 0,
    },
    {
        product_code: 'R9094953',
        product_model: '90-9495M',
        product_label: 'Kit gants bleus M',
        product_description:
            'Kit Rolock 90 with gloves 9495M, no silicone wrist seal',
        product_quantity: 0,
    },
    {
        product_code: 'R9094954',
        product_model: '90-9495L',
        product_label: 'Kit gants bleus L',
        product_description:
            'Kit Rolock 90 with gloves 9495L, no silicone wrist seal',
        product_quantity: 0,
    },
    {
        product_code: 'R9094955',
        product_model: '90-9495XL',
        product_label: 'Kit gants bleus XL',
        product_description:
            'Kit Rolock 90 with gloves 9495XL, no silicone wrist seal',
        product_quantity: 0,
    },
    {
        product_code: 'R9058093',
        product_model: '90-5809M',
        product_label: 'Kit gants latex noir M',
        product_description:
            'Kit Rolock 90 with gloves 5809M, no silicone wrist seal',
        product_quantity: 0,
    },
    {
        product_code: 'R9058104',
        product_model: '90-5810L',
        product_label: 'Kit gants latex noir L',
        product_description:
            'Kit Rolock 90 with gloves 5810L, no silicone wrist seal',
        product_quantity: 0,
    },
    {
        product_code: 'R9058115',
        product_model: '90-5811XL',
        product_label: 'Kit gants latex noir XL',
        product_description:
            'Kit Rolock 90 with gloves 5811XL, no silicone wrist seal',
        product_quantity: 0,
    },
];

export default products;
